apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ymse
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ymse
    app.kubernetes.io/part-of: byoc-app-vnmo
  name: ymse
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: ymse
status:
  loadBalancer: {}
